INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (1, 'Kanto');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (2, 'Johto');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (3, 'Hoenn');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (4, 'Sinnoh');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (5, 'Teselia');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (6, 'Kalos');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (7, 'Alola');
INSERT INTO REGION (ID_REGION, NOMBRE) VALUES (8, 'Galar');
