INSERT INTO POKEMON (ID_POKEMON, NOMBRE, ALTURA, PESO, TIPO_1, TIPO_2, ID_REGION) VALUES (1, 'bulbasaur', 7.0, 69.0, 12, 4, 1);
INSERT INTO POKEMON (ID_POKEMON, NOMBRE, ALTURA, PESO, TIPO_1, TIPO_2, ID_REGION) VALUES (2, 'ivysaur', 10.0, 130.0, 12, 4, 1);
INSERT INTO POKEMON (ID_POKEMON, NOMBRE, ALTURA, PESO, TIPO_1, TIPO_2, ID_REGION) VALUES (3, 'venusaur', 20.0, 1000.0, 12, 4, 1);
INSERT INTO POKEMON (ID_POKEMON, NOMBRE, ALTURA, PESO, TIPO_1, TIPO_2, ID_REGION) VALUES (4, 'charmander', 6.0, 85.0, 10, null, 1);
INSERT INTO POKEMON (ID_POKEMON, NOMBRE, ALTURA, PESO, TIPO_1, TIPO_2, ID_REGION) VALUES (5, 'charmeleon', 11.0, 190.0, 10, null, 1);
